### ISSUE TITLE
Incorrect allocation to variable weth_amount_out in revm_arbitrage file 

### ISSUE THREAD

**Issue by advock** [pawurb/univ3-revm-arbitrage#1]
In file revm_arbitrage file before comparing weth_amount_out with volume, weth_amount_out variable is initialized with volume. 

`let weth_amount_out = U256::from(volume);`

should be 

```
let weth_amount_out_U256 = U256::from(weth_amount_out);
weth_amount_out_U256 > volume
```

can i create a PR for this ?

**Comment by pawurb** [comment]
right, that's an oversight, please prepare a PR!

**Comment by advock** [comment]
Thank you so much.

Status: PR created

**Comment by advock** [comment]
Also Can you brief a little about how do we simulate the swap function of V3_pool if we never really initialize reserve or current state of the pool ?

LMK if I am missing something.

thanks

**Comment by pawurb** [comment]
@advock db client takes care of getting necessary storage slots

**Comment by advock** [comment]
Little confused over how it works. Can you suggest any doc or Something to understand it better.

**Comment by pawurb** [comment]
Thanks for PR! There's a related article linked, I cannot explain it better.
