### ISSUE TITLE
Custom quoter contract compilation

### ISSUE THREAD

**Issue by nodermann** [pawurb/univ3-revm-arbitrage#3]
Suppose you use the original uni_v3_quoter.hex, everything works well, but if you compile the contract via remix without changes with optimization 200, this will panic: It should never happen!

How do I compile this contract correctly?

**Comment by pawurb** [comment]
You can try `solc` or `forge build`. Also make sure to use the correct deployed bytecode format.

**Comment by nodermann** [comment]
Thank you, deleting the first 28 bytes helped.
